
[window]
title = "Term"
dimensions = { columns = 120, lines = 40 }
padding = { x = 15, y = 15 }

[font]
normal = { family = "Hurmit Nerd Font Mono", style = "Regular" }
size = 11

[terminal.shell]
program = "nu"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[general]
import = ["ayu_dark.toml"]

[terminal]

