# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v

alias vim=nvim

export FZF_DEFAULT_COMMAND='rg --files'

# Fancy function to make intermdiate directories and touch a file
function mkdir_and_touch_file() {
  local destfile=$1

  if [[ $destfile == */ ]]; then
    # If directory, just make a directory
    mkdir -p $destfile
  else
    # Else, make parent dir and touch file
    local destdir="$(dirname $destfile)"

    if [ -e "$destfile" ]; then
      echo "'$destfile' already exists." >&2
      return 2
    else
      mkdir -p "$(dirname "$1")" && touch "$1"
    fi
  fi
}

function c() {
  if [[ $# -eq 0 ]]; then
    echo "Usage: c <path> [extra paths...]"
    echo "Creates an empty file and any intermediate directories at any of the given paths."
    return 1
  fi

  for new_file in "$@"
  do
    mkdir_and_touch_file $new_file
  done
}

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
