# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v

alias vim=nvim
alias fd=fdfind

export FZF_DEFAULT_COMMAND='rg --files'

# fnm
export PATH="/home/$USER/.local/share/fnm:$PATH"
eval "`fnm env`"

# flyctl
export FLYCTL_INSTALL="/home/$USER/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
