#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v

alias vim=nvim
alias fd=fdfind

export FZF_DEFAULT_COMMAND='rg --files'

# fnm
export PATH="/home/vkon/.local/share/fnm:$PATH"
eval "`fnm env`"
