[general]
fullscreen = true
early-exit = true
copy-command = "wl-copy"
output-filename = "~/screenshots/satty-%Y%m%d-%H:%M:%S.png"
actions-on-enter = ["save-to-clipboard", "save-to-file", "exit"]
actions-on-escape = ["save-to-clipboard", "exit"]
no-window-decoration = true
