[general]
fullscreen = true
early-exit = false
copy-command = "wl-copy"
output-filename = "/home/kinetic/screenshots/satty-%d-%b-%Y-%H%M%S.png"
save-after-copy = true
actions-on-enter = ["save-to-clipboard", "exit"]
actions-on-escape = ["exit"]
no-window-decoration = true
